### ISSUE TITLE
Command-line use does not work in Windows

### ISSUE THREAD

**Issue by nextcen-dgemoets** [RDFLib/pySHACL#17] opened 2019-02-27 23:21 UTC
The path is not getting interpreted correctly:
`file://c:\my\full\path\test.ttl/ does not look like a valid URI, trying to serialize this will break.`

I've tried with forward slashes, backslashes, no slashes (all files in current directory), full filespec (with and without c:), etc.  Couldn't get any of them to work.

Windows 10.

**Comment by ashleysommer** [comment] 2019-02-27 23:34
@nextcen-dgemoets 
Thank you for this report.
I have never tested pySHACL on windows, so its not surprising to find this kind of bug occurring.
I will organise a windows VM for fixing this issue.

**Comment by ashleysommer** [comment] 2019-02-28 05:48
@nextcen-dgemoets 
I've pushed a new version of pyshacl to pypi.
v 0.9.9.post1
This is just a couple of basic changes to fix some path usage on windows. Can you please test that version to check if it solves your issue.
If it hasn't fixed it, Im sure there are more changes I can make.

**Comment by nextcen-dgemoets** [comment] 2019-02-28 16:01
Thank you for being so responsive.  Unless I did something wrong (quite possible; I'm a python novice), it didn't make a difference.  I've seen problems with other software handling Windows paths when using them as URIs (the colon character trips things up).

FWIW, currently I'm only evaluating the tool, and I can evaluate it on Linux in the meantime.

Here's the full output:
```
>python C:\Python3.7\Scripts\pyshacl --abort --shacl restrictions.shacl -f turtle minitest.ttl
file://C:\Users\dgemoets\test\minitest.ttl/ does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\test\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
Traceback (most recent call last):
  File "C:\Python3.7\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\users\dgemoets\documents\git\pyshacl\bin\pyshacl", line 81, in <module>
    is_conform, v_graph, v_text = validate(args.data, **validator_kwargs)
  File "C:\Python3.7\lib\site-packages\pyshacl\validate.py", line 209, in validate
    rdf_format=shacl_graph_format)
  File "C:\Python3.7\lib\site-packages\pyshacl\util.py", line 240, in load_into_graph
    g.parse(source=target, format=rdf_format, publicID=public_id)
  File "C:\Python3.7\lib\site-packages\rdflib\graph.py", line 1043, in parse
    parser.parse(source, self, **args)
  File "C:\Python3.7\lib\site-packages\rdflib\plugins\parsers\rdfxml.py", line 578, in parse
    self._parser.parse(source)
  File "C:\Python3.7\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\Python3.7\lib\xml\sax\xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "C:\Python3.7\lib\xml\sax\expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "C:\Python3.7\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: not well-formed (invalid token)
```

**Comment by nextcen-dgemoets** [comment] 2019-02-28 20:28
Thank you for being so responsive.  The bad news is that I am still getting these "bad URI" errors.  The good news is that it doesn't seem to be causing a problem with validation.  My bigger problem was that I needed to specify the `-sf` and `-ef` switches, and that --ont-graph only allows one file to be specified.

FWIW, currently I'm only evaluating the tool, and I can evaluate it on Linux in the meantime.

Here's the full output:
```
C:\Users\dgemoets\testdir>python C:\Python3.7\Scripts\pyshacl --abort --shacl src\main\resources\com\ncc\aif\aida_ontology.shacl -sf turtle --ont-graph ontologies\Ontology -ef turtle -ef turtle -f turtle minitest.ttl
file://C:\Users\dgemoets\testdir\minitest.ttl/ does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology/ does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\src\main\resources\com\ncc\aif\aida_ontology.shacl/ does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\src\main\resources\com\ncc\aif\aida_ontology.shacl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\minitest.ttl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\ontologies\Ontology# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\src\main\resources\com\ncc\aif\aida_ontology.shacl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\src\main\resources\com\ncc\aif\aida_ontology.shacl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\src\main\resources\com\ncc\aif\aida_ontology.shacl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\src\main\resources\com\ncc\aif\aida_ontology.shacl# does not look like a valid URI, trying to serialize this will break.
file://C:\Users\dgemoets\testdir\src\main\resources\com\ncc\aif\aida_ontology.shacl# does not look like a valid URI, trying to serialize this will break.

<prefixes deleted>

[] a sh:ValidationReport ;
    sh:conforms true .
```

**Comment by ashleysommer** [comment] 2019-03-07 01:29
@nextcen-dgemoets 
> and that --ont-graph only allows one file to be specified

Interesting you mention that about the `--ont-graph` argument.
You may not know, but the extra ontology graph-mixin feature was only added to pySHACL very recently, in the last version.
It came about because we saw cases where users were having to append ontological constructs into their data-graph before validating it, in order to have it pass in a logical way.

The SHACL specification only mentions the use of two graphs in the validation process, the 'shapes graph' and the 'data graph'. I had the idea to provide the ability in pySHACL to pull in one extra graph to mix into the 'data graph' before validation, to save users the extra step of having to add ontological constructs to their data graph themselves. I don't believe any other SHACL Validator engines provide that feature.

Its great that you've found that feature to be helpful for your use-case. Can you tell us, how would the ability to specify multiple additional mix-in ontology files help? In issue https://github.com/RDFLib/pySHACL/issues/18 we are discussing the possibility to have pySHACL honor `owl:imports` for shape-files, so one shape-file can dynamically import others as needed. Would having `owl:imports` working  on the extra ontology graph satisfy your requirement for pulling in multiple ontology files?

**Comment by ashleysommer** [comment] 2019-03-07 08:14
@nextcen-dgemoets 
I've pushed out a new version of pySHACL, `v0.9.10`
It has a couple more Windows fixes, they may or may not help the issue you are having. I'm starting to think it might be an RDFLib issue, and it may rectify itself when RDFLib 5.0 comes out later this year.
But more importantly, this release comes with `owl:imports` support. So you can define one ontology document that imports a bunch of other ontologies, as an alternative to needing to declare multiple extra ontology files.

**Comment by nextcen-dgemoets** [comment] 2019-03-08 20:04
Thank you for the update.  I think you're right about RDFLib-- like I mentioned earlier, I've seen these Windows-specific issues with URIs in the past.  I don't think the error is specific to pyShacl.

In talking with a colleague, we don't think we need any changes to the `--ont-graph` switch.  We also think that the `--import` flag was a great addition although we're not using it ourselves.

It turns out that my other problem was that we had an extra, undefined rule in our SHACL file that caused pyShacl to report invalid SHACL, whereas TopBraid didn't report an error (presumably it ignored it).  As a small enhancement request (perhaps one you've thought of before), I'd suggest more context in the error message when a SHACL error is found-- listing the invalid shape or the line number of the error.

Thank you again for your efforts!

**Comment by ashleysommer** [comment] 2019-03-08 23:38
@nextcen-dgemoets 
Thanks for the extra information.
We actually haven't done much testing around invalid Shapes in SHACL files.
All of the embedded SHACL test suite files contain only valid Shapes, so when shapes are invalid it is a bit of an Undefined Behavior situation.
Are you able to post a minimal SHACL file that reproduces that error you were seeing, plus a capture of the pySHACL output you were seeing?

BTW, you probably already know this, but you can enable meta-shacl mode in pySHACL that will validate your SHACL Shapes file to ensure it is valid before using it to validate your data. That may be useful for catching these kinds of issues, plus will give you better reporting on what the issue actually is.

**Comment by nextcen-dgemoets** [comment] 2019-03-12 22:04
I'm guessing you could take any SHACL file you already have an add a reference to a spurious/undefined shape, and you'll have the scenario I encountered.  So,
```
ex:MyShape
   sh:targetClass ex:ValidClass ;
   sh:property ex:InvalidShape ;
   sh:property ex:ValidShape ;
   .
```
The output I received was: `Validator encountered a Runtime Error:
Shape pointed to by sh:property does not exist or is not a well-formed SHACL PropertyShape.If you believe this is a bug in pyshacl, open an Issue on the pyshacl github page`

However, this was before I discovered the `--metashacl` option.  And you're right, the output with the `--metashacl` option identified the error:
```
Shacl File does not validate against the Shacl Shapes Shacl file.
Validation Report
Conforms: False
Results (1):
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:maxCount Literal("1", datatype=xsd:integer) ; sh:minCount Literal("1", datatype=xsd:integer) ; sh:node shsh:PathShape ; sh:path sh:path ]
        Focus Node: <https://example.com/OntologyName#InvalidShape>
        Result Path: sh:path

Validator encountered a Runtime Error:
Shacl File does not validate against the Shacl Shapes Shacl file.
Validation Report
Conforms: False
Results (1):
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:maxCount Literal("1", datatype=xsd:integer) ; sh:minCount Literal("1", datatype=xsd:integer) ; sh:node shsh:PathShape ; sh:path sh:path ]
        Focus Node: <https://example.com/OntologyName#InvalidShape>
        Result Path: sh:path
If you believe this is a bug in pyshacl, open an Issue on the pyshacl github page.
```

**Comment by ashleysommer** [comment] 2019-09-16 04:02
Hi @nextcen-dgemoets 
Is this issue resolved? Can we close it?

**Comment by nextcen-dgemoets** [comment] 2019-09-17 21:36
I am not using pyShacl any more, and I'm not using a pure Windows environment any more to test it.  So I guess it can be closed until further issues are reported?

**Closed** 2019-09-17 23:14 UTC
