### ISSUE TITLE
Shape with `sh:oneOrMorePath` raises a runtime error

### ISSUE THREAD

**Issue by edmondchuc** [RDFLib/pySHACL#130] opened 2022-03-08 10:17 UTC
PySHACL raises a `ShapeLoadError` when loading a `NodeShape` containing `sh:oneOrMorePath`.

I'm running pySHACL using the CLI: 
```
pyshacl -s shacl.ttl -f human data.ttl
```

#### `shacl.ttl`:

```turtle
@prefix geo: <http://www.opengis.net/ont/geosparql#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix sosa: <http://www.w3.org/ns/sosa/> .
@prefix tern: <https://w3id.org/tern/ontologies/tern/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix schema: <http://schema.org/> .

<urn:shape:observation> a sh:NodeShape ;
    sh:message "At least one sample in the chain of samples must have a spatial indicator." ;
    sh:targetClass sosa:Observation ;
    sh:property <urn:shape:Observation-hasFeatureOfInterest>
.

<urn:shape:Observation-hasFeatureOfInterest> a sh:PropertyShape ;
    sh:path sosa:hasFeatureOfInterest ;
    sh:node <urn:shape:Sample-isSampleOf>
.

<urn:shape:Sample-isSampleOf> a sh:NodeShape ;
    sh:path [
        sh:oneOrMorePath sosa:isSampleOf
    ] ;
    sh:qualifiedValueShape [
        sh:property [
            sh:path geo:hasGeometry ;
            sh:minCount 1
        ]
    ] ;
    sh:qualifiedMinCount 1
.

```

#### `data.ttl`:

```turtle
@prefix geo: <http://www.opengis.net/ont/geosparql#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix schema: <https://schema.org/> .
@prefix sosa: <http://www.w3.org/ns/sosa/> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix sosa: <http://www.w3.org/ns/sosa/> .

<urn:example:sample:1> a sosa:FeatureOfInterest ;
    geo:hasGeometry [
        a geo:Geometry ;
        geo:asWKT "POINT (1 2)"
    ] ;
.

<urn:example:sample:2> a sosa:Sample ;
    sosa:isSampleOf <urn:example:sample:1> ;
.

<urn:example:sample:3> a sosa:Sample ;
    sosa:isSampleOf <urn:example:sample:2> ;
.

<urn:example:sample:4> a sosa:Sample ;
    sosa:isSampleOf <urn:example:sample:3> ;
.

<urn:example:observation:1> a sosa:Observation ;
    sosa:hasFeatureOfInterest <urn:example:sample:4> ;
.
```

I tested the same shapes and data with [TopQuadrant/shacl](https://github.com/TopQuadrant/shacl) and it runs with no errors.

---

PySHACL Version: 0.18.1
RDFLib 6.1.1
Python 3.10.0

**Comment by edmondchuc** [comment] 2022-03-08 10:49
Okay I figured it out. The issue is `<urn:shape:Sample-isSampleOf>` is a `NodeShape` and everything connected to it should be the value of an `sh:property`. In other words, `sh:path` cannot be a property of a `NodeShape`.

Corrected shape:

```turtle
<urn:shape:Sample-isSampleOf> a sh:NodeShape ;
    sh:property [
        sh:path [
            sh:zeroOrMorePath sosa:isSampleOf
        ] ;
        sh:qualifiedValueShape [
            sh:property [
                sh:path geo:hasGeometry ;
                sh:minCount 1
            ]
        ] ;
        sh:qualifiedMinCount 1
    ]
.
```

I realised the error by chance when I commented out the `sh:path` and pySHACL provided warnings due to qualified value shape being present on a `NodeShape`.

```
ConstraintLoadWarning: QualifiedValueShapeConstraintComponent can only be present on a PropertyShape, not a NodeShape.
https://www.w3.org/TR/shacl/#QualifiedValueShapeConstraintComponent
ConstraintLoadWarning: QualifiedValueShapeConstraintComponent can only be present on a PropertyShape, not a NodeShape.
https://www.w3.org/TR/shacl/#QualifiedValueShapeConstraintComponent
```

It'd be nice if those warnings are also available when `sh:path` is declared on a `NodeShape`.

I tested this on the other SHACL implementations: [TopQuadrant/shacl](https://github.com/TopQuadrant/shacl), https://shacl.org/playground/ and https://shacl-playground.zazuko.com/. Interestingly, they don't throw any errors and run fine. I do prefer pySHACL's stricter rules but it'd be nice if the errors were more informative for debugging.

**Comment by ashleysommer** [comment] 2022-03-08 23:31
Thanks for the report Edmond.

>  I do prefer pySHACL's stricter rules

PySHACL is not intentionally stricter than other implementations. PySHACL simply does exactly what the SHACL spec outlines, it follows the reporting rules, shape error rules, and validation error rules exactly as written. If other implementations do not conform to that standard, and allow malformed Shapes to load without error, then they are buggy.

I know there is something weird going on when reporting shape load errors when running PySHACL from the CLI tool.

The informative error messages _are_ already coded in the system. When loading a NodeShape, if it has a `sh:path` value, it should print an informative `ShapeLoadError` that explains the problem, and links to the relevant part of the SHACL Spec. But for some reason, now all ShapeLoadErrors seem to crash the tool, and issue a non-helpful message. This has come up in some other PySHACL bug reports too.

So the crux of this issue, is the error reporting is bad.

**Comment by ashleysommer** [comment] 2022-03-12 09:38
Hi Edmond.
I tracked down the cause of this, it seems ShapeLoadError and ConstraintLoadError messages were being swallowed by the CLI tool, because the Exception class hierarchy wasn't set up properly (this has been a problem for a while!), so the CLI tool wasn't catching the correct exception types, and causing them to crash the application.

This is fixed now. Please test on v0.19.0, you will notice those errors are reported as expected by the CLI too.

**Closed by ashleysommer** 2022-03-12 09:38 UTC
