### ISSUE TITLE
SPARQLFunction support

### ISSUE THREAD

**Issue by James-Hudson3010** [RDFLib/pySHACL#59] opened 2020-09-02 18:40 UTC
I tried using the SHACL found at http://datashapes.org/schema.ttl to validate some data and received the following error:

> NotImplementedError: SHACL Advanced Feature SPARQLFunction is not yet supported.

I'll add my vote to getting this feature implemented.

**Comment by ashleysommer** [comment] 2020-09-02 23:46
The [SPARQLFunction](https://www.w3.org/TR/shacl-af/#functions) feature from the [SHACL Advanced Spec](https://www.w3.org/TR/shacl-af/#functions) is very complex, it would take a lot of effort to implement correctly in PySHACL. It seems to me to be a very niche feature that not many users would need or want.

However, I am happy to review and merge pull requests for features that developers want in PySHACL.

**Comment by James-Hudson3010** [comment] 2020-09-03 13:26
I ran into the issue because I wanted to use the SHACL file at http://datashapes.org/schema to help validate schema.org data instances. I am not sure why or how it is using the SPARQLFunction feature, but assuming it is required for this purpose and considering that schema.org is mainstream, I am not sure if it can be defined as niche. 

In any case, something to consider and perhaps keep an eye out for someone willing to implement it for pySHACL. 

It would appear that the shaclvalidate tool at https://repo1.maven.org/maven2/org/topbraid/shacl/1.3.2/ implements the feature so there is a solid reference implementation out there which should help anyone who takes on the task.

**Comment by ashleysommer** [comment] 2020-09-03 22:20
Hi @James-Hudson3010 
The schema.org shacl file _used_ to work fine with PySHACL. That was actually one of the SHACL files I used for testing PySHACL during development.

There must've been a recent update that added the use of SPARQLFunction. As far as I'm aware, the features from the SHACL Advanced Spec are not yet finalized, they may change before becoming a standard, and not considered stable for use in production validation systems, but that might be incorrect.

You can bypass this error if you turn off Advanced features in `pyshacl` (don't pass in the `-a` argument) this ignores all of the SHACL Advanced Spec features, and operates as if they don't exist in the SHACL file.

**Comment by ashleysommer** [comment] 2020-09-03 22:27
Actually, this might be a PySHACL bug.
I've checked the whole file, and the Schema.org SHACL file _doesn't_ use `SPARQLFunction`.

The `SPARQLFunction` advanced features is triggered by:
  * A Shape that is of type `sh:SPARQLFunction` or
  * A shape with `sh:parameter` or
  * A shape with `sh:returnType`

There are none of those in the Schema.org SHACL file. I'll have to dig a bit further to find out whats going on.

**Comment by ashleysommer** [comment] 2020-09-03 22:47
@James-Hudson3010 
I cannot reproduce this bug. I've loaded that `schema.ttl` file from Schema.org into PySHACL (with advanced mode turned on) and used it to validate several datafiles, and it works normally. It does not trigger the `SPARQLFunction is not yet supported` error because `sh:SPARQLFunction` is not used in that file.

**Comment by ashleysommer** [comment] 2020-09-03 23:30
Update:
I found it. `SPARQLFunction` is used in http://datashapes.org/dash.ttl that is imported by `schema.ttl`.
I had imports turned off, that's why I didn't see the error.
If you turn off imports, the SHACL file will not pull in `dash.ttl`, so it will not throw this error.

Side note: Dash is another extension to SHACL, which is above and beyond the SHACL Advanced Spec, there a things like dash:Scripts and dash:Actions which can execute Javascript code on the dataset, and looks like there are a couple of helper functions which are Shapes that use `SPARQLFunction` to execute SPARQL on the dataset.

I'm thinking about what will be the best way forward here. Blocking the import of `dash.ttl` is one way, but is probably too heavy handed. Perhaps for now simply ignoring any shapes from the `<http://datashapes.org/dash>` ontology might work, at least until PySHACL gets enough advanced features in order to take advantage of DASH.

**Comment by ashleysommer** [comment] 2020-09-04 14:01
I've had a one-person codeathon tonight and fully implemented `SHACLFunction` and `SPARQLFunction` in pyshacl.
Can you please try pyshacl v0.13.0 and let me know if it fixes your problem?
Closed by https://github.com/RDFLib/pySHACL/commit/cc3d291fd981d6e1a35f20559ae8ebcc7b589cb6

**Closed by ashleysommer** 2020-09-04 14:01 UTC

**Comment by James-Hudson3010** [comment] 2020-09-04 20:47
I will check it out when I get the chance.

**Comment by James-Hudson3010** [comment] 2020-09-10 11:56
Confirmed. Works for me now.
