### ISSUE TITLE
pySHACL uses deprecated API `pkg_resources`

### ISSUE THREAD

**Issue by jakebeal** [RDFLib/pySHACL#212] opened 2023-10-25 23:15 UTC
pySHACL uses a deprecated API, `pkg_resources`, which is no longer supported in some environments: https://setuptools.pypa.io/en/latest/pkg_resources.html 

We use pySHACL in a number of projects, and it is creating failures for us with Python 3.12.

Example of pySHACL causing failures due to its import of `pkg_resources`: https://github.com/SynBioDex/pySBOL3/actions/runs/6538548950/job/17754712923

**Comment by ashleysommer** [comment] 2023-11-07 09:44
This is a duplicate of #188 
There are a couple of different attempts at a fix, but it is not an easy task.
Hopefully we'll get an updated version out by next week.

**Closed by ashleysommer** 2023-11-07 09:44 UTC

**Comment by ashleysommer** [comment] 2023-11-07 14:50
Fixed by https://github.com/RDFLib/pySHACL/commit/2de29c09b1bdf801fe5b39bdb4d29e3c871266c4

**Comment by jakebeal** [comment] 2023-11-07 22:17
Thank you! I will keep my eyes out for the new version.

**Comment by ashleysommer** [comment] 2023-11-08 06:41
@jakebeal Now you don't need to wait until next week, the new version with this fix is out now.
Note, PySHACL still does not officially support python 3.12, and the application is not tested on python 3.12, so you may run into other problems.

**Comment by rmfranken** [comment] 2024-11-20 10:40
Hi @ashleysommer , is that still the case? I'm running into the pkg_resource error too, but it's been a year and we updated to pyshacl 0.26.0. the pyproject says python version >=3.9 and we're running python 3.12.3

:upside_down_face:

**Comment by ashleysommer** [comment] 2024-11-21 00:00
Hi @rmfranken 
No, that is no longer the case. PySHACL removed the use of `pkg_resources` in version v0.24.0 in early November 2023, and Python 3.12 support was added in v0.25.0 later in the same month in November 2023.

**Comment by rmfranken** [comment] 2024-11-21 11:54
Thanks for the clear response! I guess there is something going wrong on our end then, as we were under the impression that we were using 0.26.0 where this should not have been an issue any more. I will dig a little deeper to see why my local build is still trying to import it! 

In fact, I'll probably upgrade the version to latest (I inherited this code). Sorry for dredging up an old solved issue! :grimacing:
